"""create_invoices_and_payout_batches

Revision ID: 5ee0b8564096
Revises: ddb449dc097a
Create Date: 2026-08-27 18:50:08.451219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee0b8564096'
down_revision: Union[str, Sequence[str], None] = 'ddb449dc097a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_payout_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'DISBURSED', 'VOID', name='payout_batch_status_enum', native_enum=False), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_legs_count', sa.Integer(), nullable=False),
    sa.Column('gross_payout_amount', sa.Float(), nullable=False),
    sa.Column('gst_credit_amount', sa.Float(), nullable=False),
    sa.Column('withholding_tax_amount', sa.Float(), nullable=False),
    sa.Column('net_disbursed_amount', sa.Float(), nullable=False),
    sa.Column('rcti_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_payout_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_payout_batches_batch_number'), ['batch_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_driver_payout_batches_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_payout_batches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_payout_batches_status'), ['status'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'PARTIALLY_PAID', 'OVERDUE', 'VOID', 'CREDITED', name='invoice_status_enum', native_enum=False), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subtotal_ex_gst', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('total_inc_gst', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('balance_due', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    op.create_table('invoice_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_ex_gst', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('total_inc_gst', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_line_items_invoice_id'), ['invoice_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_foreign_key('fk_payments_invoice_id', 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_invoice_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_column('invoice_id')

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_id'))

    op.drop_table('invoice_line_items')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_booking_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('driver_payout_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_payout_batches_status'))
        batch_op.drop_index(batch_op.f('ix_driver_payout_batches_id'))
        batch_op.drop_index(batch_op.f('ix_driver_payout_batches_driver_id'))
        batch_op.drop_index(batch_op.f('ix_driver_payout_batches_batch_number'))

    op.drop_table('driver_payout_batches')
    # ### end Alembic commands ###
