"""add_driver_gps_and_metrics

Revision ID: 78fcdc3adc1d
Revises: 72ca2c7bb2a7
Create Date: 2026-08-27 17:52:29.488838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fcdc3adc1d'
down_revision: Union[str, Sequence[str], None] = '72ca2c7bb2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_trips_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('completed_trips_count')
        batch_op.drop_column('location_updated_at')
        batch_op.drop_column('current_lng')
        batch_op.drop_column('current_lat')

    # ### end Alembic commands ###
