"""create_partner_offers_and_compliance

Revision ID: 8acc71370590
Revises: 5ee0b8564096
Create Date: 2026-08-27 20:13:07.007892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8acc71370590'
down_revision: Union[str, Sequence[str], None] = '5ee0b8564096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_payout_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'DISBURSED', 'VOID', name='partner_payout_status_enum', native_enum=False), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_legs_count', sa.Integer(), nullable=False),
    sa.Column('gross_payout_amount', sa.Float(), nullable=False),
    sa.Column('gst_amount', sa.Float(), nullable=False),
    sa.Column('net_disbursed_amount', sa.Float(), nullable=False),
    sa.Column('rcti_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_payout_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_payout_batches_batch_number'), ['batch_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_partner_payout_batches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_payout_batches_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_payout_batches_status'), ['status'], unique=False)

    op.create_table('partner_job_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('leg_id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('offered_payout', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['leg_id'], ['booking_legs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_job_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_job_offers_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_job_offers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_job_offers_leg_id'), ['leg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_job_offers_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_job_offers_status'), ['status'], unique=False)

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_policy_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('insurance_expiry', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('accreditation_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('accreditation_expiry', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_compliance_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('is_compliance_verified')
        batch_op.drop_column('accreditation_expiry')
        batch_op.drop_column('accreditation_number')
        batch_op.drop_column('insurance_expiry')
        batch_op.drop_column('insurance_policy_number')

    with op.batch_alter_table('partner_job_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_job_offers_status'))
        batch_op.drop_index(batch_op.f('ix_partner_job_offers_partner_id'))
        batch_op.drop_index(batch_op.f('ix_partner_job_offers_leg_id'))
        batch_op.drop_index(batch_op.f('ix_partner_job_offers_id'))
        batch_op.drop_index(batch_op.f('ix_partner_job_offers_expires_at'))

    op.drop_table('partner_job_offers')
    with op.batch_alter_table('partner_payout_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_payout_batches_status'))
        batch_op.drop_index(batch_op.f('ix_partner_payout_batches_partner_id'))
        batch_op.drop_index(batch_op.f('ix_partner_payout_batches_id'))
        batch_op.drop_index(batch_op.f('ix_partner_payout_batches_batch_number'))

    op.drop_table('partner_payout_batches')
    # ### end Alembic commands ###
