"""add_pricing_and_quote_tables

Revision ID: d81c7a0e7152
Revises: f8cc4cb915ed
Create Date: 2026-08-27 16:42:18.121013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81c7a0e7152'
down_revision: Union[str, Sequence[str], None] = 'f8cc4cb915ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport_route_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('origin_keyword', sa.String(length=100), nullable=False),
    sa.Column('destination_keyword', sa.String(length=100), nullable=False),
    sa.Column('vehicle_category', sa.Enum('SEDAN_EXECUTIVE', 'SEDAN_PREMIUM', 'SUV_PREMIUM', 'PEOPLE_MOVER', 'MINIBUS', name='route_vehicle_category_enum', native_enum=False), nullable=False),
    sa.Column('all_inclusive_fare', sa.Float(), nullable=False),
    sa.Column('tolls_included', sa.Boolean(), nullable=False),
    sa.Column('airport_fee_included', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('airport_route_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airport_route_rules_destination_keyword'), ['destination_keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_airport_route_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_airport_route_rules_origin_keyword'), ['origin_keyword'], unique=False)

    op.create_table('pricing_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_category', sa.Enum('SEDAN_EXECUTIVE', 'SEDAN_PREMIUM', 'SUV_PREMIUM', 'PEOPLE_MOVER', 'MINIBUS', name='pricing_vehicle_category_enum', native_enum=False), nullable=False),
    sa.Column('base_fee', sa.Float(), nullable=False),
    sa.Column('minimum_fare', sa.Float(), nullable=False),
    sa.Column('per_km_tier1', sa.Float(), nullable=False),
    sa.Column('tier1_threshold_km', sa.Float(), nullable=False),
    sa.Column('per_km_tier2', sa.Float(), nullable=False),
    sa.Column('per_minute_rate', sa.Float(), nullable=False),
    sa.Column('airport_access_fee', sa.Float(), nullable=False),
    sa.Column('deadhead_rate_per_km', sa.Float(), nullable=False),
    sa.Column('deadhead_threshold_km', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_rules_vehicle_category'), ['vehicle_category'], unique=True)

    op.create_table('surcharge_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surcharge_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surcharge_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surcharge_rules_id'), ['id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('dropoff_address', sa.String(length=500), nullable=False),
    sa.Column('pickup_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('quote_options', sa.JSON(), nullable=False),
    sa.Column('is_all_inclusive', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_quote_number'), ['quote_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_quote_number'))
        batch_op.drop_index(batch_op.f('ix_quotes_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('surcharge_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surcharge_rules_id'))

    op.drop_table('surcharge_rules')
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_rules_vehicle_category'))
        batch_op.drop_index(batch_op.f('ix_pricing_rules_id'))

    op.drop_table('pricing_rules')
    with op.batch_alter_table('airport_route_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airport_route_rules_origin_keyword'))
        batch_op.drop_index(batch_op.f('ix_airport_route_rules_id'))
        batch_op.drop_index(batch_op.f('ix_airport_route_rules_destination_keyword'))

    op.drop_table('airport_route_rules')
    # ### end Alembic commands ###
