"""add_flight_and_wait_time_columns_to_legs

Revision ID: ddb449dc097a
Revises: 78fcdc3adc1d
Create Date: 2026-08-27 18:26:52.732482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb449dc097a'
down_revision: Union[str, Sequence[str], None] = '78fcdc3adc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_legs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_terminal', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('flight_delay_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('wait_time_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('wait_time_charge', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_legs', schema=None) as batch_op:
        batch_op.drop_column('wait_time_charge')
        batch_op.drop_column('wait_time_minutes')
        batch_op.drop_column('flight_delay_minutes')
        batch_op.drop_column('flight_terminal')

    # ### end Alembic commands ###
