"""create_core_entities

Revision ID: f8cc4cb915ed
Revises: 
Create Date: 2026-08-27 14:26:50.218317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8cc4cb915ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATIONS_MANAGER', 'DISPATCHER', 'ACCOUNTANT', 'DRIVER', 'CUSTOMER', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('SEDAN_EXECUTIVE', 'SEDAN_PREMIUM', 'SUV_PREMIUM', 'PEOPLE_MOVER', 'MINIBUS', name='vehicle_category_enum', native_enum=False), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('registration_plate', sa.String(length=20), nullable=False),
    sa.Column('passenger_capacity', sa.Integer(), nullable=False),
    sa.Column('luggage_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('insurance_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rego_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_registration_plate'), ['registration_plate'], unique=True)

    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_user_id'), ['user_id'], unique=False)

    op.create_table('drivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accreditation_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'OFF_DUTY', 'SUSPENDED', name='driver_status_enum', native_enum=False), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('default_vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_user_id'), ['user_id'], unique=True)

    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('WEBSITE', 'BOOKING_WIDGET', 'INSTANT_QUOTE', 'PHONE', 'EMAIL', 'MANUAL', 'APP', 'PARTNER', name='booking_source_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ENQUIRY', 'QUOTED', 'VERIFICATION_REQUIRED', 'PAYMENT_PENDING', 'CONFIRMED', 'ALLOCATED', 'DISPATCHED', 'EN_ROUTE', 'ARRIVED', 'PICKED_UP', 'COMPLETED', 'FINANCIALLY_CLOSED', 'CANCELLED', 'REFUND_PENDING', 'REFUNDED', name='booking_status_enum', native_enum=False), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIAL_DEPOSIT', 'PAID_IN_FULL', 'OVERDUE', 'REFUND_PENDING', 'REFUNDED', 'PARTIALLY_REFUNDED', name='payment_status_enum', native_enum=False), nullable=False),
    sa.Column('verification_status', sa.Enum('NOT_REQUIRED', 'PENDING', 'VERIFIED', 'FAILED', name='verification_status_enum', native_enum=False), nullable=False),
    sa.Column('fare_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('total_fare', sa.Float(), nullable=False),
    sa.Column('deposit_required', sa.Float(), nullable=False),
    sa.Column('deposit_percentage', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('balance_amount', sa.Float(), nullable=False),
    sa.Column('pricing_breakdown', sa.JSON(), nullable=True),
    sa.Column('flight_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('passenger_name', sa.String(length=255), nullable=True),
    sa.Column('passenger_phone', sa.String(length=50), nullable=True),
    sa.Column('passenger_email', sa.String(length=255), nullable=True),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('luggage_count', sa.Integer(), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_number'), ['booking_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_verification_status'), ['verification_status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE', 'ALLOCATION', 'PAYMENT', 'CANCELLATION', 'REFUND', name='audit_action_enum', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('booking_legs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('leg_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ALLOCATED', 'DISPATCHED', 'EN_ROUTE', 'ARRIVED', 'PICKED_UP', 'COMPLETED', 'CANCELLED', name='leg_status_enum', native_enum=False), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('dropoff_address', sa.String(length=500), nullable=False),
    sa.Column('dropoff_lat', sa.Float(), nullable=True),
    sa.Column('dropoff_lng', sa.Float(), nullable=True),
    sa.Column('pickup_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('vehicle_category', sa.Enum('SEDAN_EXECUTIVE', 'SEDAN_PREMIUM', 'SUV_PREMIUM', 'PEOPLE_MOVER', 'MINIBUS', name='leg_vehicle_category_enum', native_enum=False), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('partner_id', sa.String(length=36), nullable=True),
    sa.Column('allocation_cost', sa.Float(), nullable=False),
    sa.Column('is_airport_pickup', sa.Boolean(), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=True),
    sa.Column('flight_number', sa.String(length=50), nullable=True),
    sa.Column('flight_scheduled_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flight_actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flight_status', sa.String(length=50), nullable=True),
    sa.Column('pickup_notes', sa.Text(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('en_route_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_legs_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_legs_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_legs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_legs_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_legs_pickup_datetime'), ['pickup_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_legs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_legs_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_legs_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_booking_legs_status'))
        batch_op.drop_index(batch_op.f('ix_booking_legs_pickup_datetime'))
        batch_op.drop_index(batch_op.f('ix_booking_legs_partner_id'))
        batch_op.drop_index(batch_op.f('ix_booking_legs_id'))
        batch_op.drop_index(batch_op.f('ix_booking_legs_driver_id'))
        batch_op.drop_index(batch_op.f('ix_booking_legs_booking_id'))

    op.drop_table('booking_legs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_booking_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_verification_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_source'))
        batch_op.drop_index(batch_op.f('ix_bookings_payment_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_customer_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_number'))

    op.drop_table('bookings')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_user_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_status'))
        batch_op.drop_index(batch_op.f('ix_drivers_phone'))
        batch_op.drop_index(batch_op.f('ix_drivers_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_full_name'))
        batch_op.drop_index(batch_op.f('ix_drivers_email'))

    op.drop_table('drivers')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_user_id'))
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_full_name'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_registration_plate'))
        batch_op.drop_index(batch_op.f('ix_vehicles_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_category'))

    op.drop_table('vehicles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
